### ISSUE TITLE
3 charts do not render

### ISSUE THREAD

**Issue by jobberwalker** [SAP/openui5-charting-custom-controls#4]
Hello
The 3 charts (polarChart, pieChart, doughnutChart) do not render on Chrome.
JB

**Comment by Michadelic** [comment]
Thanks @jobberwalker for reporting this issue.
I could fix it by updating the configuration and had to adjust the class slightly.
lowercasing the chart type did not work for the polarArea chart.

See you and Kind Regards,
Michael
